<template><div><p>Escribir un texto científico requiere un nivel de precisión y organización que va más allá de un documento convencional. <VPIcon icon="vscode-icons:file-type-word" /> Microsoft Word, aunque parezca una herramienta sencilla, ofrece funciones avanzadas que transforman el proceso de redacción en un flujo de trabajo profesional y automatizado.</p>
<h2 id="_1bs06-configuro-mis-estilos-de-caracter" tabindex="-1"><a class="header-anchor" href="#_1bs06-configuro-mis-estilos-de-caracter"><span>1BS06: Configuro mis estilos de carácter</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 13 al 17 de Abril<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-word" /> Microsoft Word<br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Crea un estudio sobre los problemas de Tiktok en la inteligencia<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=j5QsRpJFhc8" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1voayhvvJ2cu5CA5afu5yvcyC0vBCgZQE?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Los Estilos en Microsoft Word son una herramienta fundamental para dar formato, estructurar y mantener la consistencia visual de cualquier documento de manera profesional y eficiente. En lugar de modificar manualmente la fuente, el tamaño, el color o el espaciado de cada título o párrafo de forma individual, los estilos te permiten aplicar una combinación predefinida de todos estos formatos con un solo clic. Más allá de garantizar un diseño uniforme y ahorrar un tiempo invaluable, su uso (especialmente el de los estilos de &quot;Título&quot;) es el pilar indispensable para desbloquear las funciones más potentes del procesador de texto, como la generación automática de tablas de contenido (índices) y la navegación rápida a través de la estructura del documento.</p>
<h2 id="_1bs07-configuro-mis-estilos-de-parrafo-mkd" tabindex="-1"><a class="header-anchor" href="#_1bs07-configuro-mis-estilos-de-parrafo-mkd"><span>1BS07: Configuro mis estilos de párrafo (MKD)</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 20 al 24 de Abril<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-word" /> Microsoft Word<br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Ver el final<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=77Ggk1uzO2A" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1voayhvvJ2cu5CA5afu5yvcyC0vBCgZQE?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Markdown se presenta como una alternativa minimalista y altamente eficiente frente a procesadores de texto complejos como Microsoft Word, cambiando el enfoque del diseño visual a la escritura fluida en texto plano. Utilizando una sintaxis muy sencilla basada en signos de puntuación comunes (como asteriscos para las negritas o almohadillas para los títulos), Markdown te permite estructurar tu documento sin tener que despegar las manos del teclado ni navegar por menús pesados. Esta separación radical entre el contenido y el formato no solo elimina las distracciones y los clásicos problemas de desconfiguración de Word, sino que garantiza la creación de archivos universales, ultraligeros y listos para ser transformados al instante en páginas web (HTML), documentos PDF o ser integrados en sistemas de gestión de contenido.</p>
<div class="hint-container warning">
<p class="hint-container-title"><strong>Tarea</strong></p>
<p>Formatea el documento de la semana 6 en Markdown</p>
</div>
<h2 id="_1bs08-anado-los-encabezados-y-pies-de-pagina" tabindex="-1"><a class="header-anchor" href="#_1bs08-anado-los-encabezados-y-pies-de-pagina"><span>1BS08: Añado los encabezados y pies de página</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 27 al 30 de Abril<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-word" /> Microsoft Word<br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Sin tarea<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=aF8zVzM90VM" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1voayhvvJ2cu5CA5afu5yvcyC0vBCgZQE?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Los Encabezados en Microsoft Word son áreas reservadas en el margen superior de cada página, diseñadas para mostrar información clave que se repite de manera automática a lo largo de todo el documento. Su propósito fundamental es enriquecer la presentación visual y mantener el contexto sin interrumpir el texto principal, permitiéndote insertar elementos constantes como el título del trabajo, el nombre del autor, logotipos institucionales, fechas o la numeración de las páginas. Al utilizar esta herramienta, no solo aportas un alto nivel de profesionalismo y orden a tus proyectos, sino que estableces un marco de identidad uniforme que resulta indispensable para la presentación formal de ensayos, informes técnicos o guías educativas extensas.</p>
<h2 id="_1bs09-practica-calificada-revision-de-folder" tabindex="-1"><a class="header-anchor" href="#_1bs09-practica-calificada-revision-de-folder"><span>1BS09: Práctica Calificada &amp; Revisión de Folder</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> Semana 9<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-word" /> Microsoft Word<br></p>
</div>
<p>Busca el archivo <code v-pre>TRADICIONES PERUANAS DE RICARDO PALMA.docx</code>en la carpeta de recursos, agregale el formato APA según la página usada en clase, presenta tu proyecto al profesor.</p>
</div></template>


