<template><div><p>Esta sección corresponde al segundo grado de educación secundaria. Los recursos y programas usados se detallan a continuación:</p>
<h2 id="_1-programas-a-usar" tabindex="-1"><a class="header-anchor" href="#_1-programas-a-usar"><span>1. Programas a usar</span></a></h2>
<p>El alumno deberá tener instalado en sus computadoras los programas siguientes para el desarrollo de las tareas en casa. La lista corresponde a los programas que se usarán en todo el año.</p>
<ul>
<li><VPIcon icon="logos:visual-studio-code" /> <strong>Visual Studio Code:</strong> Es un editor de código fuente ligero pero muy potente, desarrollado por Microsoft, que permite programar en múltiples lenguajes como JavaScript, Python, C++, Java, entre otros. Ofrece una interfaz moderna, personalizable con temas y extensiones, integración con Git, depuración en tiempo real y funciones inteligentes como autocompletado y resaltado de sintaxis. Es multiplataforma (Windows, macOS y Linux) y se ha convertido en una de las herramientas favoritas de desarrolladores por su rapidez, flexibilidad y la gran comunidad que constantemente crea nuevas extensiones para mejorar su funcionalidad. Puedes instalarlo de manera gratuita desde esta <a href="https://code.visualstudio.com/" target="_blank" rel="noopener noreferrer">página web</a>.</li>
<li><VPIcon icon="streamline-flex-color:cat-2" /> <strong>Cat JS:</strong> Es un motor de videojuegos 2D moderno, gratuito y de código abierto, pensado para hacer que aprender programación y crear juegos sea accesible y divertido. Combina potentes herramientas visuales con un entorno de desarrollo completo: incluye un editor visual de niveles con soporte de tilemaps, animaciones en tiempo real, y un sistema visual de partículas. Además, cuenta con un editor de código estilo Visual Studio Code que permite escribir en JavaScript, TypeScript, CoffeeScript o su lenguaje visual Catnip, ofreciendo autocompletado, depuración avanzada e integración de documentación directamente en el entorno. Puedes descargarlo de manera gratuita desde esta <a href="https://ctjs.rocks/download/" target="_blank" rel="noopener noreferrer">página web</a>.</li>
<li><VPIcon icon="simple-icons:lmms" color="#26A65C" /> <strong>LMMS:</strong> Es un software libre y multiplataforma para la creación de música digital. Funciona como una estación de trabajo de audio (DAW) que permite componer, mezclar y producir canciones usando sintetizadores, samples, efectos y plugins VST. Su interfaz es intuitiva y 0está organizada en editores como el de patrones, el de canciones y el de mezcla, lo que facilita la producción incluso a principiantes. Es muy usado por músicos independientes porque ofrece herramientas potentes sin necesidad de licencias de pago, siendo una alternativa gratuita a programas como FL Studio o Ableton Live. Puedes instalarlo de manera gratuita desde esta <a href="https://ctjs.rocks/download/" target="_blank" rel="noopener noreferrer">página web</a>.</li>
<li><VPIcon icon="devicon:illustrator" /> <strong>Illustrator</strong> / <VPIcon icon="simple-icons:photopea" color="#18a497" /> <strong><a href="https://www.photopea.com/" target="_blank" rel="noopener noreferrer">Photopea</a></strong>: Adobe Illustrator es un programa profesional de diseño gráfico especializado en la creación de ilustraciones vectoriales. Se usa ampliamente en publicidad, diseño de logotipos, tipografías, iconos, ilustraciones y gráficos que requieren gran calidad y escalabilidad sin pérdida de resolución. Ofrece herramientas avanzadas de dibujo, manejo de colores, pinceles personalizados y compatibilidad con otros programas de Adobe, lo que lo convierte en un estándar de la industria del diseño.Photopea, en cambio, es un editor de imágenes en línea, gratuito y muy versátil, que funciona directamente desde el navegador sin necesidad de instalar nada. Es compatible con formatos como PSD, XCF, Sketch, AI y más, permitiendo editar fotografías, diseñar gráficos y trabajar con capas de forma muy similar a Photoshop. Por su accesibilidad y potencia, se ha convertido en una herramienta popular para estudiantes, diseñadores y cualquier persona que necesite editar imágenes sin pagar licencias costosas.</li>
<li><VPIcon icon="mdi:microsoft-office" color="red" /> <strong>Office:</strong> Es una de las suites de productividad más utilizadas en el mundo, desarrollada por Microsoft. Incluye programas esenciales como Word (procesador de texto), Excel (hojas de cálculo), PowerPoint (presentaciones), Outlook (correo electrónico y calendario) y otros complementos según la versión. Está disponible para Windows, macOS y en versión en línea, ofreciendo colaboración en tiempo real y almacenamiento en la nube mediante OneDrive. Su principal ventaja es que reúne en un solo paquete herramientas para escribir documentos, organizar datos, crear presentaciones profesionales y comunicarse de manera eficiente, siendo indispensable tanto en entornos educativos como empresariales. Puedes instalar a partir de la versión 2015.</li>
</ul>
<h2 id="_2-secciones" tabindex="-1"><a class="header-anchor" href="#_2-secciones"><span>2. Secciones</span></a></h2>
<h3 id="bimestre-i" tabindex="-1"><a class="header-anchor" href="#bimestre-i"><span>Bimestre I</span></a></h3>
<ul>
<li><VPIcon icon="fluent-color:notebook-32" /> <a href="./1-bimestre/unidad-1">Unidad 1</a></li>
</ul>
</div></template>


