<template><div><p><VPIcon icon="dashicons:wordpress" color="#21759b" /> WordPress es un sistema de gestión de contenidos (CMS, por sus siglas en inglés) que permite crear y administrar sitios web de manera sencilla, sin necesidad de tener conocimientos avanzados de programación. Fue lanzado en 2003 y, con el tiempo, se ha convertido en una de las herramientas más populares del mundo para diseñar blogs, portafolios, tiendas virtuales y páginas empresariales.</p>
<h2 id="_4bs05-instalo-un-tema-gratuito" tabindex="-1"><a class="header-anchor" href="#_4bs05-instalo-un-tema-gratuito"><span>4BS05: Instalo un tema gratuito</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 17 al 21 de Noviembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="dashicons:wordpress" color="#21759b" /> <a href="https://es.wordpress.org/download/" target="_blank" rel="noopener noreferrer">Wordpress</a> / <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Configura Astra en tu sitio web<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=6CcQsTpvNE4" target="_blank" rel="noopener noreferrer">Astra</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1sS6GGJK9ZJz4Go2m57zzpjfSGLDMH5jn?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>El tema Astra es uno de los más populares y versátiles dentro del ecosistema de WordPress, reconocido por su ligereza, velocidad y amplias posibilidades de personalización. Diseñado para funcionar tanto con editores visuales como Elementor, Gutenberg o Beaver Builder, permite crear sitios profesionales sin necesidad de conocimientos avanzados de programación. Gracias a sus plantillas prediseñadas, compatibilidad con plugins esenciales y su enfoque en el rendimiento, Astra se convierte en una excelente opción para quienes desean construir páginas web modernas, rápidas y totalmente adaptables a cualquier necesidad.</p>
<h2 id="_4bs06-configuro-menus-y-widgets" tabindex="-1"><a class="header-anchor" href="#_4bs06-configuro-menus-y-widgets"><span>4BS06: Configuro menús y widgets</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 24 al 28 de Noviembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="dashicons:wordpress" color="#21759b" /> <a href="https://es.wordpress.org/download/" target="_blank" rel="noopener noreferrer">Wordpress</a> / <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Crear el mençu principal en tu sitio web<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=p4VUmQlEy8I" target="_blank" rel="noopener noreferrer">Spectra</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1sS6GGJK9ZJz4Go2m57zzpjfSGLDMH5jn?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Los menús y widgets en WordPress son herramientas esenciales para organizar y enriquecer la navegación de un sitio web sin necesidad de conocimientos avanzados de programación. Los menús permiten estructurar las páginas, entradas y enlaces personalizados de forma clara, facilitando que los visitantes encuentren rápidamente la información que buscan. Por su parte, los widgets añaden funcionalidades extra —como buscadores, listas de categorías, imágenes, formularios o textos personalizados— en áreas específicas del tema, como barras laterales o pies de página. En conjunto, ambos elementos ayudan a mejorar la experiencia del usuario, hacer el sitio más intuitivo y aprovechar al máximo las capacidades del tema instalado.</p>
<h2 id="_4bs07-instalo-los-plugins-basicos" tabindex="-1"><a class="header-anchor" href="#_4bs07-instalo-los-plugins-basicos"><span>4BS07: Instalo los plugins básicos</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 01 al 05 de Diciembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="dashicons:wordpress" color="#21759b" /> <a href="https://es.wordpress.org/download/" target="_blank" rel="noopener noreferrer">Wordpress</a> / <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Terminar la página principal de tu sitio web.<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=p4VUmQlEy8I" target="_blank" rel="noopener noreferrer">Spectra</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1sS6GGJK9ZJz4Go2m57zzpjfSGLDMH5jn?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Spectre es una herramienta que facilita la edición visual y personalizada de páginas en WordPress, permitiendo construir diseños modernos sin necesidad de código. Con su interfaz intuitiva, el usuario puede modificar la página de inicio, agregar secciones, reorganizar elementos y ajustar estilos de manera rápida mediante bloques o componentes prediseñados. Esta flexibilidad convierte a Spectre en un aliado ideal para crear sitios web atractivos, optimizados y coherentes con la identidad del proyecto, incluso para quienes recién comienzan en el diseño web.</p>
<h2 id="_4bs08-completo-mi-sitio-web-y-lo-publico-en-linea" tabindex="-1"><a class="header-anchor" href="#_4bs08-completo-mi-sitio-web-y-lo-publico-en-linea"><span>4BS08: Completo mi sitio web y lo publico en línea</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 08 al 12 de Diciembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="dashicons:wordpress" color="#21759b" /> <a href="https://es.wordpress.org/download/" target="_blank" rel="noopener noreferrer">Wordpress</a> / <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Terminar la página principal de tu sitio web.<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=p4VUmQlEy8I" target="_blank" rel="noopener noreferrer">Spectra</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1sS6GGJK9ZJz4Go2m57zzpjfSGLDMH5jn?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Publicar un sitio web en WordPress es el paso final para hacer visible tu proyecto en Internet y permitir que cualquier usuario pueda acceder a su contenido. Este proceso implica configurar correctamente el hosting, enlazar tu dominio, ajustar los parámetros de visibilidad y asegurarte de que todos los elementos del sitio —como menús, páginas, plugins y temas— estén listos para funcionar de manera óptima. Una vez publicado, tu sitio se convierte en una plataforma activa donde podrás compartir información, ofrecer servicios o interactuar con tus visitantes, aprovechando toda la flexibilidad y potencia que ofrece WordPress.</p>
<h2 id="_4bs09-practica-final" tabindex="-1"><a class="header-anchor" href="#_4bs09-practica-final"><span>4BS09: Práctica Final</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 13 de Diciembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="dashicons:wordpress" color="#21759b" /> <a href="https://es.wordpress.org/download/" target="_blank" rel="noopener noreferrer">Wordpress</a> / <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a></p>
</div>
<p>Se te revisará tu sitio web creado por el profesor, el cual debe tener lo siguiente:</p>
<ul>
<li>Páginas: Principal, Acerca de, Blog.</li>
<li>Entradas: 10 entradas de similar temática del sitio.</li>
<li>Página inicial: Principal</li>
<li>Página de entradas: Blog.</li>
<li>Enlaces Permanentes: blog_name/%category%/%postname%</li>
<li>La página principal debe tener como mínimo diez secciones y acerca de 5 como mínimo.</li>
</ul>
</div></template>


