<template><div><p><VPIcon icon="dashicons:wordpress" color="#21759b" /> WordPress es un sistema de gestión de contenidos (CMS, por sus siglas en inglés) que permite crear y administrar sitios web de manera sencilla, sin necesidad de tener conocimientos avanzados de programación. Fue lanzado en 2003 y, con el tiempo, se ha convertido en una de las herramientas más populares del mundo para diseñar blogs, portafolios, tiendas virtuales y páginas empresariales.</p>
<h2 id="_4bs05-configuro-menus-y-widgets" tabindex="-1"><a class="header-anchor" href="#_4bs05-configuro-menus-y-widgets"><span>4BS05: Configuro menús y widgets</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 17 al 21 de Noviembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="dashicons:wordpress" color="#21759b" /> <a href="https://es.wordpress.org/download/" target="_blank" rel="noopener noreferrer">Wordpress</a> / <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Crear el mençu principal en tu sitio web<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=p4VUmQlEy8I" target="_blank" rel="noopener noreferrer">Spectra</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1sS6GGJK9ZJz4Go2m57zzpjfSGLDMH5jn?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Los menús y widgets en WordPress son herramientas esenciales para organizar y enriquecer la navegación de un sitio web sin necesidad de conocimientos avanzados de programación. Los menús permiten estructurar las páginas, entradas y enlaces personalizados de forma clara, facilitando que los visitantes encuentren rápidamente la información que buscan. Por su parte, los widgets añaden funcionalidades extra —como buscadores, listas de categorías, imágenes, formularios o textos personalizados— en áreas específicas del tema, como barras laterales o pies de página. En conjunto, ambos elementos ayudan a mejorar la experiencia del usuario, hacer el sitio más intuitivo y aprovechar al máximo las capacidades del tema instalado.</p>
<h2 id="_4bs06-instalo-los-plugins-basicos" tabindex="-1"><a class="header-anchor" href="#_4bs06-instalo-los-plugins-basicos"><span>4BS06: Instalo los plugins básicos</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 24 al 28 de Noviembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="dashicons:wordpress" color="#21759b" /> <a href="https://es.wordpress.org/download/" target="_blank" rel="noopener noreferrer">Wordpress</a> / <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Terminar la página principal de tu sitio web.<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=p4VUmQlEy8I" target="_blank" rel="noopener noreferrer">Spectra</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1sS6GGJK9ZJz4Go2m57zzpjfSGLDMH5jn?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Spectre es una herramienta que facilita la edición visual y personalizada de páginas en WordPress, permitiendo construir diseños modernos sin necesidad de código. Con su interfaz intuitiva, el usuario puede modificar la página de inicio, agregar secciones, reorganizar elementos y ajustar estilos de manera rápida mediante bloques o componentes prediseñados. Esta flexibilidad convierte a Spectre en un aliado ideal para crear sitios web atractivos, optimizados y coherentes con la identidad del proyecto, incluso para quienes recién comienzan en el diseño web.</p>
</div></template>


