<template><div><p>¡Bienvenidos al fascinante mundo del diseño digital con <VPIcon icon="simple-icons:photopea" color="#18A497" /> Photopea! Esta herramienta es una de las plataformas de edición de imágenes más completas y accesibles que existen hoy en día. A diferencia de otros programas que requieren instalaciones pesadas o licencias costosas, Photopea funciona directamente desde tu navegador, brindándote el poder de un software profesional totalmente gratis y al alcance de un clic.</p>
<p>Con Photopea, descubrirás que no hay límites para tu imaginación. Aprenderás a trabajar con capas, a utilizar herramientas de precisión como la pluma, a aplicar filtros avanzados y a gestionar formatos profesionales como PSD, AI o PDF. Ya sea que quieras retocar una fotografía, diseñar un logotipo desde cero o crear contenido para redes sociales, esta plataforma te ofrece todas las funciones necesarias para transformar tus ideas en piezas visuales de alta calidad, preparándote con habilidades técnicas que se utilizan en la industria del diseño en todo el mundo.</p>
<h2 id="_1bs01-creo-un-emoji-con-formas-basicas" tabindex="-1"><a class="header-anchor" href="#_1bs01-creo-un-emoji-con-formas-basicas"><span>1BS01: Creo un emoji con formas básicas</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 09 al 13 de Marzo<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:photopea" color="#18A497" /> <a href="https://www.photopea.com/" target="_blank" rel="noopener noreferrer">Photopea</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Sin tarea<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://youtube.com/playlist?list=PLOuPFNSnWxurrTVHXXtyNvkZD9ZroHqDA" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1xQE1cxdSxjQYRbnzP0LhML1X9ZoCNs27?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>¡Dale vida a tus propios iconos con Photopea! Esta potente herramienta, accesible directamente desde el navegador, nos abre las puertas al diseño gráfico profesional sin necesidad de instalaciones complejas. Al crear emojis, aprenderás a dominar el uso de capas, herramientas de dibujo vectorial y la gestión de la transparencia para lograr acabados impecables.</p>
<h2 id="_3bs02-vectorizo-una-imagen-basica" tabindex="-1"><a class="header-anchor" href="#_3bs02-vectorizo-una-imagen-basica"><span>3BS02: Vectorizo una imagen básica</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 16 al 20 de Marzo<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:photopea" color="#18A497" /> <a href="https://www.photopea.com/" target="_blank" rel="noopener noreferrer">Photopea</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Sin tarea<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://youtube.com/playlist?list=PLOuPFNSnWxurrTVHXXtyNvkZD9ZroHqDA" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1xQE1cxdSxjQYRbnzP0LhML1X9ZoCNs27?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>La herramienta Pluma es, sin duda, una de las funciones más potentes y versátiles que encontrarás en Photopea. A diferencia del pincel o el borrador, la Pluma no depende de tu pulso manual, sino de la creación de nodos o puntos de anclaje que generan trazados vectoriales matemáticamente perfectos. Esto la convierte en el recurso indispensable para realizar selecciones de alta precisión, recortar objetos complejos con bordes limpios o diseñar logotipos y formas personalizadas desde cero.</p>
<h2 id="_3bs03-anado-efectos-usando-mascara-de-recorte-y-de-capa" tabindex="-1"><a class="header-anchor" href="#_3bs03-anado-efectos-usando-mascara-de-recorte-y-de-capa"><span>3BS03: Añado efectos usando máscara de recorte y de capa</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 23 al 27 de Marzo<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:photopea" color="#18A497" /> <a href="https://www.photopea.com/" target="_blank" rel="noopener noreferrer">Photopea</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Ver al final<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://youtube.com/playlist?list=PLOuPFNSnWxurrTVHXXtyNvkZD9ZroHqDA" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1xQE1cxdSxjQYRbnzP0LhML1X9ZoCNs27?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Las máscaras de capa son una de las herramientas más poderosas y esenciales en el mundo del diseño digital, ya que nos permiten trabajar con una &quot;edición no destructiva&quot;. A diferencia del borrador, que elimina los píxeles para siempre, una máscara actúa como una capa invisible que nos permite ocultar o revelar partes de una imagen sin perder la información original. Es, en esencia, tener el control total sobre la visibilidad de nuestros elementos.El secreto de las máscaras es muy sencillo de recordar: &quot;El negro esconde y el blanco revela&quot;. Al pintar con estos colores sobre la máscara, podemos fusionar dos imágenes de forma suave, crear efectos de transparencia complejos o corregir errores en un recorte sin miedo a arruinar el trabajo previo. Dominar las máscaras no solo te ahorrará tiempo, sino que elevará la calidad de tus proyectos al permitirte experimentar con total libertad creativa, sabiendo que siempre puedes recuperar lo que has ocultado.</p>
<div class="hint-container warning">
<p class="hint-container-title"><strong>Tarea</strong></p>
<p>Replica lo hecho en clase, imprime y adjuntalo en tu folder para la revisión del profesor</p>
</div>
<h2 id="_3bs04-comprendo-el-uso-de-las-opciones-de-fusion" tabindex="-1"><a class="header-anchor" href="#_3bs04-comprendo-el-uso-de-las-opciones-de-fusion"><span>3BS04: Comprendo el uso de las opciones de fusión</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 30 de Marzo al 03 de Abril<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:photopea" color="#18A497" /> <a href="https://www.photopea.com/" target="_blank" rel="noopener noreferrer">Photopea</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Sin tarea<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://youtube.com/playlist?list=PLOuPFNSnWxurrTVHXXtyNvkZD9ZroHqDA" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1xQE1cxdSxjQYRbnzP0LhML1X9ZoCNs27?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>El uso de las opciones de fusión en Photopea permite combinar capas de diferentes maneras para lograr efectos visuales atractivos y profesionales. Estas opciones, también conocidas como modos de fusión, controlan cómo interactúan los colores y la iluminación entre una capa y otra, permitiendo crear sombras, brillos, transparencias y mezclas de color. Herramientas como “Multiplicar”, “Superponer” o “Trama” son esenciales para mejorar imágenes, diseñar composiciones creativas y dar mayor profundidad a los proyectos gráficos. Dominar estas funciones es clave para aprovechar al máximo el potencial de edición que ofrece Photopea.</p>
<h2 id="_3bs05-practica-calificada-revision-de-folder" tabindex="-1"><a class="header-anchor" href="#_3bs05-practica-calificada-revision-de-folder"><span>3BS05: Práctica Calificada &amp; Revisión de Folder</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> Clase de la semana 6<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:photopea" color="#18A497" /> <a href="https://www.photopea.com/" target="_blank" rel="noopener noreferrer">Photopea</a></p>
</div>
<p>Al igual que se trabajo a Pikachu, haz lo mismo con Clefairy, el pokemon hada. Imprime el trabajo final, asi como las capas que usaste. Es decir, presentarás dos hojas para esta práctica.</p>
</div></template>


