<template><div><p>Esta sección corresponde al primer grado de educación secundaria. Los recursos y programas usados se detallan a continuación:</p>
<h2 id="_1-programas-a-usar" tabindex="-1"><a class="header-anchor" href="#_1-programas-a-usar"><span>1. Programas a usar</span></a></h2>
<p>El alumno deberá tener instalado en sus computadoras los programas siguientes para el desarrollo de las tareas en casa. La lista corresponde a los programas que se usarán en todo el año.</p>
<ul>
<li><VPIcon icon="mdi:microsoft-office" color="red" /> <strong>Office:</strong> Es una de las suites de productividad más utilizadas en el mundo, desarrollada por Microsoft. Incluye programas esenciales como Word (procesador de texto), Excel (hojas de cálculo), PowerPoint (presentaciones), Outlook (correo electrónico y calendario) y otros complementos según la versión. Está disponible para Windows, macOS y en versión en línea, ofreciendo colaboración en tiempo real y almacenamiento en la nube mediante OneDrive. Su principal ventaja es que reúne en un solo paquete herramientas para escribir documentos, organizar datos, crear presentaciones profesionales y comunicarse de manera eficiente, siendo indispensable tanto en entornos educativos como empresariales. A partir de la versión 2015 en adelante.</li>
<li><VPIcon icon="simple-icons:photopea" color="#18a497" /> <strong>Photopea</strong> / <VPIcon icon="devicon:photoshop" /> <strong>Photoshop:</strong> Es un programa de edición y retoque de imágenes considerado el estándar en el mundo del diseño gráfico y la fotografía digital. Permite manipular fotografías, crear composiciones, trabajar con ilustraciones y gráficos gracias a sus herramientas de selección, capas, filtros y pinceles avanzados. Es ampliamente utilizado por fotógrafos, diseñadores, publicistas y creadores de contenido para realizar desde simples ajustes de color hasta complejas ediciones artísticas. Además, ofrece compatibilidad con tabletas gráficas, integración con otros programas de Adobe y soporte para múltiples formatos, lo que lo convierte en una herramienta esencial en el ámbito creativo profesional. Photopea se puede usar directamente desde el <a href="https://www.photopea.com/" target="_blank" rel="noopener noreferrer">navegador</a>. Photoshop, por el contrario hay que instalar.</li>
<li><VPIcon icon="devicon:illustrator" /> <strong>Illustrator</strong>: Es un programa profesional de diseño gráfico especializado en la creación de ilustraciones vectoriales. Se usa ampliamente en publicidad, diseño de logotipos, tipografías, iconos, ilustraciones y gráficos que requieren gran calidad y escalabilidad sin pérdida de resolución. Ofrece herramientas avanzadas de dibujo, manejo de colores, pinceles personalizados y compatibilidad con otros programas de Adobe, lo que lo convierte en un estándar de la industria del diseño. Puedes instalarlo o en su defecto usar <a href="https://www.photopea.com/" target="_blank" rel="noopener noreferrer">Photopea</a> o el mismo Photoshop.</li>
</ul>
<h2 id="_2-secciones" tabindex="-1"><a class="header-anchor" href="#_2-secciones"><span>2. Secciones</span></a></h2>
<h3 id="bimestre-iii" tabindex="-1"><a class="header-anchor" href="#bimestre-iii"><span>Bimestre III</span></a></h3>
<ul>
<li><VPIcon icon="fluent-color:notebook-32" /> <a href="./3-bimestre/unidad-5">Unidad 5</a></li>
<li><VPIcon icon="fluent-color:notebook-32" /> <a href="./3-bimestre/unidad-6">Unidad 6</a></li>
</ul>
</div></template>


