<template><div><p><VPIcon icon="ph:ghost" /> Wick Editor es una herramienta gratuita y en línea que permite crear animaciones interactivas y videojuegos 2D de manera sencilla. Su entorno combina lo mejor de la animación tradicional con la programación básica, lo que lo convierte en una excelente opción para aficionados.</p>
<h2 id="_4bs05-edito-mi-animacion-de-nieve" tabindex="-1"><a class="header-anchor" href="#_4bs05-edito-mi-animacion-de-nieve"><span>4BS05: Edito mi animación de nieve</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 17 al 21 de Noviembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="ph:ghost" /> <a href="https://www.wickeditor.com/#/" target="_blank" rel="noopener noreferrer">Wick Editor</a> / <a href="https://candlestickers.app/" target="_blank" rel="noopener noreferrer">Candlestickers</a><br> <VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Sin tarea<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/@lucacodes" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1JwTqjosoVEP21Pe63xg7g-G1pPczXET8?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>En Wick Editor, la creación de clones permite duplicar objetos o personajes para generar efectos dinámicos, animaciones repetitivas o interacciones más complejas sin necesidad de dibujar cada elemento manualmente. A través de código sencillo, es posible producir múltiples copias que se comporten de manera similar al objeto original o que ejecuten acciones personalizadas, lo que facilita la construcción de escenas ricas en movimiento. Esta herramienta resulta especialmente útil para crear enjambres, partículas, multitudes o patrones visuales, optimizando el tiempo de trabajo y ampliando las posibilidades creativas dentro de las animaciones.</p>
<h2 id="_4bs06-diseno-un-cielo-con-estrellas-animado" tabindex="-1"><a class="header-anchor" href="#_4bs06-diseno-un-cielo-con-estrellas-animado"><span>4BS06: Diseño un cielo con estrellas animado</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 24 al 28 de Noviembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="ph:ghost" /> <a href="https://www.wickeditor.com/#/" target="_blank" rel="noopener noreferrer">Wick Editor</a> / <a href="https://candlestickers.app/" target="_blank" rel="noopener noreferrer">Candlestickers</a><br> <VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Ver al final<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://youtu.be/PWXLSS6uErY" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1JwTqjosoVEP21Pe63xg7g-G1pPczXET8?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>Mediante la combinación de dibujos básicos, movimientos automáticos y técnicas como la duplicación o el uso de clones, es posible generar un fondo dinámico donde las estrellas parpadean o se desplazan suavemente, simulando un cielo nocturno vivo. Este tipo de animación ayuda a comprender los principios de repetición, aleatoriedad y capas, mientras se desarrolla la creatividad y el control del tiempo dentro de la línea de animación.</p>
</div></template>


