<template><div><p><VPIcon icon="mdi:wordpress" color="#0F88BD" /> WordPress es el sistema de gestión de contenidos (CMS) más popular y versátil del mundo, diseñado para permitir la creación, administración y publicación de sitios web de manera sencilla y profesional. Aunque nació originalmente como una plataforma enfocada en la creación de blogs, su arquitectura de código abierto ha evolucionado hasta convertirse en una herramienta integral capaz de dar vida a cualquier tipo de proyecto digital, desde portafolios personales y sitios corporativos hasta complejas tiendas virtuales.</p>
<h2 id="_1bs06-uso-y-preparo-imagenes-para-cargar-en-mi-sitio-web" tabindex="-1"><a class="header-anchor" href="#_1bs06-uso-y-preparo-imagenes-para-cargar-en-mi-sitio-web"><span>1BS06: Uso y preparo imágenes para cargar en mi sitio web</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 13 al 17 de Abril<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="mdi:wordpress" color="#0F88BD" /> <a href="https://pe.wordpress.org/" target="_blank" rel="noopener noreferrer">Wordpress</a> /  <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Replica lo hecho en clase en tu sitio.<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=-dDNCZtKAn0" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1PZFcDRsIkn81WQUMvHLm6P0vTOw9OX1F?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a> / <a href="https://colegio.cylea.pe/" target="_blank" rel="noopener noreferrer">Tu sitio</a></p>
</div>
<p>La optimización de imágenes en WordPress es un proceso técnico fundamental para garantizar que un sitio web cargue de manera rápida y fluida sin sacrificar su calidad visual. Aunque las fotografías y gráficos de alta resolución son esenciales para retener la atención de la audiencia, los archivos demasiado pesados son la causa número uno de lentitud en las páginas web, lo que incrementa las tasas de abandono y penaliza drásticamente el posicionamiento SEO en buscadores como Google. Optimizar consiste en encontrar el equilibrio perfecto: redimensionar las imágenes a las medidas exactas que requiere el diseño antes de subirlas, comprimir los datos ocultos de los archivos y utilizar formatos de próxima generación (como WebP o AVIF). Ya sea de forma manual o mediante plugins automatizados, aplicar estas prácticas es indispensable para construir plataformas digitales ágiles que ofrezcan una excelente experiencia de navegación.</p>
<p>Cosas a tomar en cuenta:</p>
<ul>
<li>Nombres descriptivos y fáciles de leer.</li>
<li>Formatos modernos como <code v-pre>WEBP</code> o <code v-pre>AVIF</code>.</li>
<li>Texto <code v-pre>alt</code> fácil de identificar.</li>
</ul>
<h2 id="_1bs07-comprendo-el-uso-del-elemento-container-de-mi-sitio-web" tabindex="-1"><a class="header-anchor" href="#_1bs07-comprendo-el-uso-del-elemento-container-de-mi-sitio-web"><span>1BS07: Comprendo el uso del elemento container de mi sitio web</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 20 al 24 de Abril<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="mdi:wordpress" color="#0F88BD" /> <a href="https://pe.wordpress.org/" target="_blank" rel="noopener noreferrer">Wordpress</a> /  <VPIcon icon="logos:xampp" /> <a href="https://www.apachefriends.org/es/index.html" target="_blank" rel="noopener noreferrer">Xampp</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Replica lo hecho en clase en tu sitio.<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://www.youtube.com/watch?v=-dDNCZtKAn0" target="_blank" rel="noopener noreferrer">Video</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/1PZFcDRsIkn81WQUMvHLm6P0vTOw9OX1F?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a> / <a href="https://colegio.cylea.pe/" target="_blank" rel="noopener noreferrer">Tu sitio</a></p>
</div>
<p>El bloque Container en Spectra constituye la piedra angular del diseño web moderno dentro del editor de bloques de WordPress (Gutenberg). Basado en la tecnología de Flexbox, este elemento actúa como una estructura inteligente que permite agrupar, alinear y distribuir otros bloques con una precisión y flexibilidad sin precedentes. A diferencia de las columnas tradicionales, los contenedores ofrecen un control exhaustivo sobre el espaciado, la dirección del flujo de contenido y la adaptabilidad responsiva, permitiendo que los layouts se ajusten de forma fluida a cualquier tamaño de dispositivo sin necesidad de escribir código personalizado.</p>
</div></template>


