import "D:/PEPITO-DESCARGAS/DOCS-HOPE/my-docs/node_modules/@vuepress/highlighter-helper/lib/client/styles/base.css"
import "D:/PEPITO-DESCARGAS/DOCS-HOPE/my-docs/node_modules/@vuepress/plugin-shiki/lib/client/styles/shiki.css"
import "D:/PEPITO-DESCARGAS/DOCS-HOPE/my-docs/node_modules/@vuepress/highlighter-helper/lib/client/styles/line-numbers.css"
import "D:/PEPITO-DESCARGAS/DOCS-HOPE/my-docs/node_modules/@vuepress/highlighter-helper/lib/client/styles/notation-highlight.css"
import "D:/PEPITO-DESCARGAS/DOCS-HOPE/my-docs/node_modules/@vuepress/highlighter-helper/lib/client/styles/code-block-title.css"