<template><div><p><VPIcon icon="simple-icons:scratch" color="orange" /> <a href="https://scratch.mit.edu/" target="_blank" rel="noopener noreferrer">Scratch</a> es un programa diseñado para aprender a programar de forma sencilla y divertida. Permite crear historias interactivas, juegos y animaciones mediante bloques de colores que se encajan como piezas de un rompecabezas. Gracias a su entorno visual, los estudiantes desarrollan el pensamiento lógico y la creatividad sin necesidad de escribir código complejo, convirtiéndose en una excelente herramienta para iniciarse en la programación.</p>
<h2 id="_4bs01-animo-mi-nombre-usando-bloques-basicos" tabindex="-1"><a class="header-anchor" href="#_4bs01-animo-mi-nombre-usando-bloques-basicos"><span>4BS01: Animo mi nombre usando bloques básicos</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 20 al 24 de Octubre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:scratch" color="orange" /> <a href="https://scratch.mit.edu/" target="_blank" rel="noopener noreferrer">Scratch</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Completar ficha de la semana<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="#">Tutorial</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/10cxwbVxQBSv9XlYYGcz1sEEj8yMJEa-o?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>La programación basada en bloques de Scratch utiliza piezas gráficas de colores que representan instrucciones. Estas se arrastran y encajan entre sí como si fueran fichas de rompecabezas, lo que permite crear secuencias lógicas sin escribir código. Cada bloque cumple una función específica, como mover un personaje, reproducir sonidos o tomar decisiones. Este enfoque visual facilita el aprendizaje de conceptos fundamentales de la programación, como bucles, condiciones y eventos, de una manera intuitiva y accesible para todos.</p>
<h2 id="_4bs02-creo-un-personaje-interactivo" tabindex="-1"><a class="header-anchor" href="#_4bs02-creo-un-personaje-interactivo"><span>4BS02: Creo un personaje interactivo</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 27 al 31 de Octubre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:scratch" color="orange" /> <a href="https://scratch.mit.edu/" target="_blank" rel="noopener noreferrer">Scratch</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Completar ficha de la semana<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="#">Tutorial</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/10cxwbVxQBSv9XlYYGcz1sEEj8yMJEa-o?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>En este proyecto aprenderás los pasos básicos para crear tu propio personaje interactivo en Scratch: desde el diseño del sprite y la programación de sus movimientos, hasta la incorporación de efectos visuales y sonidos que harán tu animación mucho más atractiva. ¡Prepárate para combinar creatividad y lógica para construir un personaje que cobre vida con tus propias instrucciones!</p>
<h2 id="_4bs03-programo-un-juego-de-laberinto" tabindex="-1"><a class="header-anchor" href="#_4bs03-programo-un-juego-de-laberinto"><span>4BS03: Programo un juego de laberinto</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 03 al 07 de Noviembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:scratch" color="orange" /> <a href="https://scratch.mit.edu/" target="_blank" rel="noopener noreferrer">Scratch</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Completar ficha de la semana<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="https://youtu.be/oDI0GLVZ16M" target="_blank" rel="noopener noreferrer">Tutorial</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/10cxwbVxQBSv9XlYYGcz1sEEj8yMJEa-o?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>En este proyecto, diseñaremos un recorrido lleno de caminos y obstáculos que el jugador debe superar moviendo un personaje hasta llegar a la meta. A lo largo del proceso, se aplican conceptos básicos como movimiento con teclas, detección de colisiones, control de eventos y uso de variables.</p>
<h2 id="_4bs04-practica-calificada-revision-de-folder" tabindex="-1"><a class="header-anchor" href="#_4bs04-practica-calificada-revision-de-folder"><span>4BS04: Práctica Calificada &amp; Revisión de folder</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> Semana 5<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="simple-icons:scratch" color="orange" /> <a href="https://scratch.mit.edu/" target="_blank" rel="noopener noreferrer">Scratch</a></p>
</div>
<p>Se te evaluará en la sala de Computo la semana 4. Práctica todo lo aprendido.</p>
</div></template>


