<template><div><p>Excalidraw es una herramienta en línea que permite crear diagramas, bocetos y esquemas de manera sencilla y colaborativa. Su principal atractivo es que combina la simplicidad de un lienzo digital con un estilo de dibujo a mano alzada, lo que la hace ideal para plasmar ideas rápidamente en reuniones, clases o proyectos creativos. Con Excalidraw puedes trabajar individualmente o en tiempo real con otras personas, utilizando formas, flechas, textos e imágenes para organizar conceptos de forma clara y visual. Además, al ser una aplicación gratuita y de código abierto, resulta accesible para estudiantes, docentes, diseñadores y cualquier persona que desee comunicar sus ideas de manera gráfica e intuitiva.</p>
<h2 id="_3bs06-diseno-un-cartel-informativo-en-excalidraw" tabindex="-1"><a class="header-anchor" href="#_3bs06-diseno-un-cartel-informativo-en-excalidraw"><span>3BS06: Diseño un cartel informativo en Excalidraw</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 15 al 19 de Setiembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="material-icon-theme:excalidraw" /> <a href="https://excalidraw.com/" target="_blank" rel="noopener noreferrer">Excalidraw</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Completar ficha de la semana<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="#">Tutorial</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/10cxwbVxQBSv9XlYYGcz1sEEj8yMJEa-o?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>El uso de Excalidraw para diseñar un cartel resulta práctico y accesible, especialmente en contextos educativos o creativos donde se busca transmitir información de forma clara y atractiva. La aplicación permite combinar textos, formas, flechas, íconos e incluso imágenes importadas para estructurar el contenido del cartel de manera organizada. Gracias a su estilo visual de trazo a mano, el diseño adquiere un aspecto dinámico y cercano, ideal para captar la atención. Además, es posible trabajar de manera colaborativa, lo que facilita que un grupo de estudiantes o diseñadores aporten ideas y modifiquen el cartel en tiempo real. Finalmente, el resultado se puede exportar en formatos de imagen o SVG, listos para imprimir o compartir en medios digitales.</p>
</div></template>


