<template><div><p><VPIcon icon="vscode-icons:file-type-drawio" /> <a href="http://Draw.io" target="_blank" rel="noopener noreferrer">Draw.io</a> es un programa muy útil que te ayudará a organizar tus ideas y trabajos de manera visual. Con esta herramienta puedes crear mapas conceptuales, diagramas y esquemas usando cuadros, flechas y figuras que se conectan entre sí. Es como dibujar en tu cuaderno, pero en la computadora, con la ventaja de que puedes mover, cambiar colores y modificar todo fácilmente. Su uso es sencillo y no necesitas instalar nada, ya que funciona desde internet. Con <a href="http://Draw.io" target="_blank" rel="noopener noreferrer">Draw.io</a> podrás representar tus aprendizajes de forma clara y creativa, haciendo que estudiar y explicar sea mucho más divertido.</p>
<h2 id="_3bs01-conozco-la-interfaz-de-draw-io" tabindex="-1"><a class="header-anchor" href="#_3bs01-conozco-la-interfaz-de-draw-io"><span>3BS01: Conozco la interfaz de <a href="http://draw.io" target="_blank" rel="noopener noreferrer">draw.io</a></span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 11 al 15 de Agosto<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-drawio" /> <a href="https://app.diagrams.net/" target="_blank" rel="noopener noreferrer">Draw.io</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Completar ficha de la semana<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="#">Tutorial</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/10cxwbVxQBSv9XlYYGcz1sEEj8yMJEa-o?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p><a href="http://Draw.io" target="_blank" rel="noopener noreferrer">Draw.io</a>, también conocido como <a href="http://diagrams.net" target="_blank" rel="noopener noreferrer">diagrams.net</a>, es una herramienta gratuita y en línea que permite crear diagramas de manera sencilla, rápida y visual. Es ideal para representar ideas, procesos, estructuras o flujos de trabajo mediante esquemas como mapas mentales, diagramas de flujo, organigramas, planos y más. Su interfaz intuitiva permite arrastrar y soltar elementos, personalizar formas, colores y conexiones, y guardar el trabajo tanto en la nube (Google Drive, OneDrive, etc.) como en el propio dispositivo.</p>
<h2 id="_3bs02-creo-mi-primer-mapa-conceptual" tabindex="-1"><a class="header-anchor" href="#_3bs02-creo-mi-primer-mapa-conceptual"><span>3BS02: Creo mi primer mapa conceptual</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 18 al 22 de Agosto<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-drawio" /> <a href="https://app.diagrams.net/" target="_blank" rel="noopener noreferrer">Draw.io</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Completar ficha de la semana<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="#">Tutorial</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/10cxwbVxQBSv9XlYYGcz1sEEj8yMJEa-o?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p><a href="http://Draw.io" target="_blank" rel="noopener noreferrer">Draw.io</a> es una herramienta en línea gratuita y muy versátil que permite crear diagramas de manera sencilla y rápida, ideal para elaborar mapas conceptuales. Su interfaz intuitiva ofrece una amplia variedad de formas, conectores y estilos que facilitan la organización visual de ideas y conceptos, permitiendo establecer relaciones claras entre ellos. Además, al ser una aplicación web, no requiere instalación y ofrece la posibilidad de guardar los trabajos directamente en la nube, como en Google Drive o OneDrive, lo que la convierte en una opción práctica y accesible para estudiantes y profesionales que buscan representar información de forma ordenada y visualmente atractiva.</p>
<h2 id="_3bs03-diseno-una-tabla-de-mis-materias-favoritas" tabindex="-1"><a class="header-anchor" href="#_3bs03-diseno-una-tabla-de-mis-materias-favoritas"><span>3BS03: Diseño una tabla de mis materias favoritas</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 25 al 29 de Agosto<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-drawio" /> <a href="https://app.diagrams.net/" target="_blank" rel="noopener noreferrer">Draw.io</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Completar ficha de la semana<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="#">Tutorial</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/10cxwbVxQBSv9XlYYGcz1sEEj8yMJEa-o?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p>En <a href="http://draw.io" target="_blank" rel="noopener noreferrer">draw.io</a>, las tablas son una herramienta muy útil para organizar información de manera clara y visual dentro de un diagrama. Permiten dividir datos en filas y columnas, facilitando la comparación de elementos, la clasificación de ideas o la creación de estructuras más ordenadas, como cronogramas, matrices o cuadros de roles. Su uso es sencillo: se insertan desde el menú de formas y luego se pueden personalizar cambiando colores, tamaños de celdas, bordes y estilos. Gracias a esto, las tablas en <a href="http://draw.io" target="_blank" rel="noopener noreferrer">draw.io</a> no solo cumplen una función informativa, sino que también ayudan a mejorar la presentación visual de cualquier proyecto o esquema.</p>
<h2 id="_3bs04-elaboro-un-diagrama-de-red" tabindex="-1"><a class="header-anchor" href="#_3bs04-elaboro-un-diagrama-de-red"><span>3BS04: Elaboro un diagrama de red</span></a></h2>
<div class="hint-container important">
<p class="hint-container-title">Importante</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha:</strong> 01 al 05 de Setiembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-drawio" /> <a href="https://app.diagrams.net/" target="_blank" rel="noopener noreferrer">Draw.io</a><br><VPIcon icon="fluent-color:clipboard-text-edit-32" /> <strong>Tarea:</strong> Completar ficha de la semana<br><VPIcon icon="fluent-color:video-48" /> <strong>Videos:</strong> <a href="#">Tutorial</a><br><VPIcon icon="fluent-color:briefcase-48" /> <strong>Recursos:</strong> <a href="https://drive.google.com/drive/folders/10cxwbVxQBSv9XlYYGcz1sEEj8yMJEa-o?usp=sharing" target="_blank" rel="noopener noreferrer">Recursos</a></p>
</div>
<p><a href="http://Draw.io" target="_blank" rel="noopener noreferrer">Draw.io</a> (hoy conocido también como <a href="http://diagrams.net" target="_blank" rel="noopener noreferrer">diagrams.net</a>) es una herramienta en línea gratuita que permite crear diagramas de manera sencilla y visual. Para la elaboración de diagramas de red, resulta especialmente útil porque ofrece una amplia biblioteca de íconos y símbolos estandarizados que representan dispositivos como computadoras, routers, servidores o conexiones. Su interfaz es intuitiva, basada en arrastrar y soltar, lo que facilita a los estudiantes y profesionales organizar gráficamente la estructura de una red, comprender cómo se interconectan los distintos componentes y documentar de forma clara la arquitectura de sistemas informáticos.</p>
<h2 id="_3bs05-practica-calificada-revision-de-folder" tabindex="-1"><a class="header-anchor" href="#_3bs05-practica-calificada-revision-de-folder"><span>3BS05: Practica Calificada - Revisión de Folder</span></a></h2>
<div class="hint-container caution">
<p class="hint-container-title">Advertencia</p>
<p><VPIcon icon="fluent-color:calendar-48" /> <strong>Fecha Límite:</strong> 15 de Setiembre<br><VPIcon icon="fluent-color:laptop-48" /> <strong>Programa:</strong> <VPIcon icon="vscode-icons:file-type-drawio" /> <a href="https://app.diagrams.net/" target="_blank" rel="noopener noreferrer">Draw.io</a></p>
</div>
<p>En <a href="http://draw.io" target="_blank" rel="noopener noreferrer">draw.io</a> realiza el siguiente <a href="https://files.pucp.education/puntoedu/wp-content/uploads/2021/01/23005509/riva-aguero-pucp002-1024x678.jpg" target="_blank" rel="noopener noreferrer">diagrama</a> sobre los viajes de la Riva Aguero. Expórtalo en formato PNG, imprime tu proyecto y preséntalo en la semana 6.</p>
</div></template>


